PetStoreWebClient/Controllers/PetFoodController.cs
using PetStoreWebClient.ModelClass;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PetStoreWebClient.Controllers
{
    public class PetFoodController : Controller
    {
        // GET: PetFood
        public ActionResult Index(int page = 1, int pageSize = 1)
        {
            var productView = new ProductViewHome();
            int totalRecord = 0;
            ViewBag.viewPetFoodSaleOff = productView.getViewPetFoodSaleOff();
            var allPetfood = new PetFoodModel().getAllPetFood(ref totalRecord, page, pageSize);

            ViewBag.Total = totalRecord;
            ViewBag.Page = page;

            int maxPage = 5;//maximum page link display on website
            int totalPage = 0;
            totalPage = (int)Math.Ceiling((double) totalRecord / pageSize);

            ViewBag.totalPage = totalPage;
            ViewBag.maxPage = maxPage;
            ViewBag.first = 1;
            ViewBag.last = totalPage;
            ViewBag.next = page + 1;
            ViewBag.prev = page - 1;

            return View(allPetfood);
        }

        public ActionResult Detail(String pfID)
        {

            var petfoodDetail = new PetFoodModel().getPetFoodByID(pfID);
            ViewBag.relatedPetFood = new PetFoodModel().getPetFoodRelated(petfoodDetail.pf_id);
            return View(petfoodDetail);
        }
    }
}

PetStoreWebClient/Views/PetFood/Detail.cshtml
@model PetStoreWebClient.EF.PetFood
@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var relatedPetfood = (List<PetStoreWebClient.EF.PetFood>)ViewBag.relatedPetFood;
}

<div class="content">
    <div class="section group">
        <div class="cont-desc span_1_of_2">
            <div class="product-details">
                <div class="grid images_3_of_2">
                    <div id="container">
                        <div id="products_example">
                            <div id="products">
                                <div class="slides_container">
                                    <a href="#" target="_blank"><img src="~/Assets/images/@Model.pf_image" alt=" " /></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="desc span_3_of_2">
                    <h2>@Model.pf_name</h2>
                    <div class="price">
                        <p>Price: <span>@Model.pf_salePrice.Value.ToString("N0")đ</span></p>
                    </div>
                    <div class="share-desc">
                        <div class="share">
                            <p>Share Product :</p>
                            <ul>
                                <li><a href="#"><img src="~/Assets/images/facebook.png" alt="" /></a></li>
                                <li><a href="#"><img src="~/Assets/images/twitter.png" alt="" /></a></li>
                            </ul>
                        </div>
                        <div class="button"><span><a href="/add-to-cart?productID=@Model.pf_id&Quantity=1">Add to Cart</a></span></div>
                        <div class="clear"></div>
                    </div>
                </div>
                <div class="clear"></div>
            </div>
            <div class="content_bottom">
                <div class="heading">
                    <h3>Related Products</h3>
                </div>
                <div class="see">
                    <p><a href="#">See all Products</a></p>
                </div>
                <div class="clear"></div>
            </div>
            <div class="section group">
                @foreach (var item in relatedPetfood)
                {
                    var url = "/detail/petfood/" + item.pf_id;
                    <div class="grid_1_of_4 images_1_of_4">
                        <a href="@url"><img src="~/Assets/images/@item.pf_image" alt=""></a>
                        <div class="price" style="border:none">
                            <div class="add-cart" style="float:none">
                                <h4><a href="/add-to-cart?productID=@item.pf_id&Quantity=1l">Add to Cart</a></h4>
                            </div>
                            <div class="clear"></div>
                        </div>
                    </div>
                }
            </div>
        </div>
        <div class="rightsidebar span_3_of_1">
            <h2>Products</h2>
            <ul class="side-w3ls">
                <li>@Html.ActionLink("Pet", "Index", "Home")</li>
                <li>@Html.ActionLink("Pet's food", "Index", "PetFood")</li>
                <li><a href="#">Pet's Toys</a></li>
                <li><a href="#">Pet's Medicine</a></li>
            </ul>
            <div class="subscribe">
                <h2>Newsletters Signup</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod.......</p>
                <div class="signup">
                    <form>
                        <input type="text" value="E-mail address" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'E-mail address';"><input type="submit" value="Sign up">
                    </form>
                </div>
            </div>
            <div class="community-poll">
                <h2>Community POll</h2>
                <p>What is the main reason for you to purchase products online?</p>
                <div class="poll">
                    <form>
                        <ul>
                            <li>
                                <input type="radio" name="vote" class="radio" value="1">
                                <span class="label"><label>More convenient shipping and delivery </label></span>
                            </li>
                            <li>
                                <input type="radio" name="vote" class="radio" value="2">
                                <span class="label"><label for="vote_2">Lower price</label></span>
                            </li>
                            <li>
                                <input type="radio" name="vote" class="radio" value="3">
                                <span class="label"><label for="vote_3">Bigger choice</label></span>
                            </li>
                            <li>
                                <input type="radio" name="vote" class="radio" value="5">
                                <span class="label"><label for="vote_5">Payments security </label></span>
                            </li>
                            <li>
                                <input type="radio" name="vote" class="radio" value="6">
                                <span class="label"><label for="vote_6">30-day Money Back Guarantee </label></span>
                            </li>
                            <li>
                                <input type="radio" name="vote" class="radio" value="7">
                                <span class="label"><label for="vote_7">Other.</label></span>
                            </li>
                        </ul>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

PetStoreWebClient/Views/PetFood/Index.cshtml
@model List<PetStoreWebClient.EF.PetFood>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var viewPFSaleOff = (List<PetStoreWebClient.EF.PetFood>)ViewBag.viewPetFoodSaleOff;
}

@section search{
    <div class="search_box">
    <form>
        <input type="text" value="Search" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search';}"><input type="submit" value="">
    </form>
</div>
}

@section slide{
    <div class="header_slide">
        <div class="header_bottom_left">
            <div class="categories">
                <ul>
                    <h3>Products</h3>
                    <li>@Html.ActionLink("Pet", "Index", "Pet")</li>
                    <li>@Html.ActionLink("Pet's food", "Index", "PetFood")</li>
                    <li><a href="#">Pet's accessories</a></li>
                    <li><a href="#">Pet's Toys</a></li>
                    <li><a href="#">Pet's Medicine</a></li>
                </ul>
            </div>
        </div>
        <div class="header_bottom_right">
            <div class="slider">
                <div id="slider">
                    <div id="mover">
                        @foreach (var item in viewPFSaleOff)
                        {
                            double disRate = (double)(100 - ((item.pf_salePrice * 100) / item.pf_prices));
                            int disPrice = (int)(item.pf_prices - item.pf_salePrice);
                            <div id="slide-1" class="slide">
                                <div class="slider-img">
                                    <a href="#"><img class="petfood-slide-image" src="~/Assets/images/@item.pf_image" alt="learn more" /></a>
                                </div>
                                <div class="slider-text">
                                    <h1>@item.pf_name<br><span>SALE</span></h1>
                                    <h2>UPTo @disRate% OFF</h2>
                                    <div class="features_list">
                                        <h4>@item.pf_salePrice.Value.ToString("N0")đ (-@disPrice.ToString("N0")đ)</h4>
                                    </div>
                                    <a href="/add-to-cart?productID=@item.pf_id&Quantity=1" class="btn btn-danger">Buy Now</a>
                                </div>
                                <div class="clear"></div>
                            </div>
                        }
                    </div>
                </div>
                <div class="clear"></div>
            </div>
        </div>
        <div class="clear"></div>
    </div>
}
<div class="content">
    <div class="content_top">
        <div class="heading">
            <h3>Pet's Food</h3>
        </div>
        <div class="see">
            <p><a href="#">See all Products</a></p>
        </div>
        <div class="clear"></div>
    </div>
    <div class="section group">
        @foreach (var item in Model)
        {
            var url = "/detail/petfood/" + item.pf_id;
            <div class="grid_1_of_4 images_1_of_4">
                <a href="@url"><img src="~/Assets/images/@item.pf_image" alt="" /></a>
                <h2>@item.pf_name</h2>
                <div class="price-details">
                    <div class="price-number">
                        <p><span class="rupees">@item.pf_salePrice.Value.ToString("N0")đ</span></p>
                    </div>
                    <div class="add-cart">
                        <h4><a href="/add-to-cart?productID=@item.pf_id&Quantity=1">Add to Cart</a></h4>
                    </div>
                    <div class="clear"></div>
                </div>
            </div>
        }
        <div class="clear"></div>
        <!--Phân trang-->
        @if (ViewBag.totalPage > 1)
        {
            var pageDisplay = (int)ViewBag.maxPage;
            int totalPage = (int)ViewBag.totalPage;
            int currentPage = (int)ViewBag.Page;

            //Create numberic link
            var startPageIndex = Math.Max(1, currentPage - pageDisplay / 2);
            var endPageINdex = Math.Min(totalPage, currentPage + pageDisplay / 2);

            var url = "/petfood/list";
            <ul class="pagination" style="float: right">
                @if (currentPage > ViewBag.first)
                {
                    <li class="page-item"><a class="page-link" href="@url?page=@ViewBag.first" title="First page" ><i class="fa fa-angle-double-left" aria-hidden="true"></i></a></li>
                    <li class="page-item"><a class="page-link" href="@url?page=@ViewBag.prev" title="Previous page" ><i class="fa fa-angle-left" aria-hidden="true"></i></a></li>
                }
                @for (int i = startPageIndex; i <= endPageINdex; i++)
                {
                    if (i == currentPage)
                    {
                        <li class="page-item active"><a class="page-link" href="@url?page=@i" title="Page @i">@i</a></li>
                    }
                    else
                    {
                        <li class="page-item"><a class="page-link" href="@url?page=@i" title="Page @i">@i</a></li>
                    }
                }
                @if (currentPage < totalPage)
                {
                    <li class="page-item"><a class="page-link" href="@url?page=@ViewBag.next" title="Next page" ><i class="fa fa-angle-right" aria-hidden="true"></i></a></li>
                    <li class="page-item"><a class="page-link" href="@url?page=@ViewBag.last" title="Last page" ><i class="fa fa-angle-double-right" aria-hidden="true"></i></a></li>
                }
            </ul>
        }
        else
        {
            <span class="alert alert-danger">Dont have any item</span>
        }
    </div>
</div>